---
title: "Rclub2017_spring_Kazu"
author: "Kazu"
date: "5/3/2017"
output: 
  html_document: 
    keep_md: yes
---
# Prerequisites
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2);library(tidyverse)
```
# 3.6
```{r}
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
              
ggplot(data = mpg) +
  geom_smooth(mapping = aes(x = displ, y = hwy, group = drv))
    
ggplot(data = mpg) +
  geom_smooth(
    mapping = aes(x = displ, y = hwy, group = drv)
  )
# multiple geoms
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy)) +
  geom_smooth(mapping = aes(x = displ, y = hwy))
# filter
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(mapping = aes(color = class)) + 
  geom_smooth(data = filter(mpg, class == "subcompact"), se = FALSE)
```
# 3.6 Exercises
```{r}
#1. What geom would you use to draw a line chart? A boxplot? A histogram? An area chart?
?geom_line()
?geom_boxplot() #or
?geom_violin()
?geom_area()
#2. Run this code in your head and predict what the output will look like. Then, run the code in R and check your predictions.
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) + 
  geom_point()
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) + 
  geom_point() + 
  geom_smooth(se = FALSE)
#3. What does show.legend = FALSE do? What happens if you remove it?
ggplot() + 
  geom_point(data = mpg, mapping = aes(x = displ, y = hwy, color = drv),show.legend=FALSE)
  geom_smooth(data = mpg, mapping = aes(x = displ, y = hwy, color = drv),se = FALSE,show.legend=FALSE)
# Why do you think I used it earlier in the chapter?
# with default
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class))
# show.legend=FALSE (no legend)
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, color = class),show.legend=FALSE)
#4. What does the se argument to geom_smooth() do?
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, color = drv)) + 
  geom_point() + 
  geom_smooth(se = TRUE) #  displaying confidence interval around smooth

#5. Will these two graphs look different? Why/why not?
# the same. The first one shared data and aes setting, while the second one used the same data and aes in different geom.
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth()

ggplot() + 
  geom_point(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_smooth(data = mpg, mapping = aes(x = displ, y = hwy))
#6. Recreate the R code necessary to generate the following graphs.
p1<-ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point() + 
  geom_smooth(se=FALSE)
p2<-ggplot(data = mpg, mapping = aes(x = displ, y = hwy,group=drv)) + 
  geom_point() + 
  geom_smooth(se=FALSE)
p3<-ggplot(data = mpg, mapping = aes(x = displ,
                                     y = hwy,group=drv,color=drv)) + 
  geom_point() + 
  geom_smooth(se=FALSE)
p4<-ggplot(data = mpg, mapping = aes(x = displ, y = hwy,color=drv)) + 
  geom_point() + 
  geom_smooth(aes(group=FALSE),se=FALSE)
p5<-ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point(aes(color=drv)) + 
  geom_smooth(se=FALSE,aes(linetype=drv))
p6<-ggplot() + 
  geom_point(data = mpg, mapping = aes(x = displ, y = hwy,fill=drv),shape = 21,size=5,stroke=2,colour="white") 
library(cowplot)
plot.all<-plot_grid(p1,p2,p3,p4,p5,p6,
  ncol=2,nrow=3,labels=c("A","B","C","D","E","F"),rel_widths=c(1,1,1,1,1,1)
  )
save_plot("/Volumes/data_work/Data6/bioconductor_R/Rclub2017_spring/Rclub-r4ds_Kazu.Nozue/R-club-May-3/3.6.6.png", plot.all, ncol = 2, nrow = 3,base_aspect_ratio = 0.8)

```
# my own data
```{r}
# load function
plot.bar7 <- function(trait,data.input=data.plot,title="",ylabel,rownum=3,save.plot=T,show.plot=F,width=8,height=6,RFRratio=F) { 
  #make bar chart for a trait in Kazu's data
  if (title=="") title <- trait
  data.plot<-data.input[grep(paste("(^",trait,")\\w+(rCol)",sep=""),names(data.input),value=T)]
  print(data.plot)
  # names(data.plot)<-"diff" # Kazu added this line    
  data.plot$gene <- data.input$plant  
  # #Calculate difference between sun and shade to
  #sort plot
  #data.plot$dif <- (get(paste(trait,"shade",sep="_"),data.plot) -
  # # get(paste(trait,"sun",sep="_"),data.plot))
  data.plot$dif<-data.plot[,grep("sun_mean",names(data.plot))[grep("sun_mean",names(data.plot)) %in% grep("_rCol_rsun",names(data.plot))]]-data.plot[,grep("shade_mean",names(data.plot))[grep("shade_mean",names(data.plot)) %in% grep("_rCol_rsun",names(data.plot))]]    
  print("data.plot$dif is")
  print(data.plot$dif)     
  print("names(data.plot) are")
  print(names(data.plot))  
  # order according to response (data.plot$dif) # this is off in SA plot
  #data.plot <- data.plot[order(data.plot$dif),] 
  #print("ordered data is")
  print(data.plot)
  # #will need to preserve this ordering
  data.plot$rank <- 1:dim(data.plot)[1]  
  #subset and rearrange data
  data.plot.sun <- data.plot[c(grep("(_sun)",names(data.plot),value=T)[grep("(_sun)",names(data.plot)) %in% grep("(_rsun)",names(data.plot))],"gene","rank")]
  print("names(data.plot.sun) are")
  
  print(names(data.plot.sun))
  data.plot.shade <- data.plot[c(grep("(_shade)",names(data.plot),value=T)[grep("(_shade)",names(data.plot)) %in% grep("(_rshade)",names(data.plot))],"gene","rank")]
  print("names(data.plot.shade) are");print(names(data.plot.shade))
  data.plot.sun$trt <- "sun"
  data.plot.shade$trt <- "shade"
  names(data.plot.sun)[1:3] <- c("mean","SE","pvalue")
  names(data.plot.shade)[1:3] <- c("mean","SE","pvalue") # this pvalue is not "response" 
  # input response pvalue
  data.plot.shade$"pvalue"<-data.plot[,grep("(_shade_pvalue_rCol_rsun)",names(data.plot))]
  
  data.plot <- rbind(data.plot.sun,data.plot.shade)
  # if (length(data.plot)!=7) {
  # warning(paste("incorrect number of data columns for trait",trait,"not plotting"))
  # return()
  # }
  print("rearragend data.plot is");print(data.plot)
  data.plot$trt <- factor(data.plot$trt,levels=c("sun","shade"))
  data.plot$gene <- factor(data.plot$gene,levels=data.plot.sun$gene)
  data.plot$ymin=data.plot$mean - data.plot$SE
  data.plot$ymax=data.plot$mean + data.plot$SE
  
  # add significance label (p<0.05)
  data.plot$significance<-" "
  data.plot$significance[data.plot$pvalue<0.05]<-"*"
  # remove significance in Col in sun
  data.plot[data.plot$gene=="Col"&data.plot$trt=="sun","significance"]<-" "
  
  if(RFRratio) {
    data.plot$trt<-gsub("sun","high \nR/FR",as.character(data.plot$trt))
    data.plot$trt<-gsub("shade","low \nR/FR",as.character(data.plot$trt))
    data.plot$trt<-factor(data.plot$trt,levels=c("high \nR/FR","low \nR/FR"))
  } 
  
  print(data.plot)
  pl <- ggplot(data=data.plot)
  pl <- pl + geom_bar(mapping=aes(fill=trt,x=trt,y=mean),stat="identity")
  pl <- pl + facet_wrap(facets=~gene,nrow=rownum)
  pl <- pl + geom_errorbar(mapping=aes(x=trt,ymin=ymin,ymax=ymax))
  #  pl <- pl + opts(strip.text.x = theme_text(angle=90))
  pl <- pl + theme(strip.text.x = element_text(angle=90))
  #pl <- pl + theme(strip.text.x = element_text(angle=90,colour=data.plot$gene))
  pl <- pl + theme(strip.text.x = element_text(colour=data.plot$gene))
  #pl <- pl + opts(axis.title.x = theme_blank(), axis.title.y = theme_blank(),title=title)
  pl <-pl + theme(axis.title.x = element_blank(), axis.text.x=element_text(angle=90))
  pl <-pl + labs(title=title,y=ylabel)
  pl <- pl + geom_text(data=data.plot,aes(x=trt,y=ymax*1.05,label=factor(significance),color=trt))     # for significance
  pl
  if(save.plot) ggsave(filename=paste(title,"pdf",sep="."),
                       plot=pl,width=width,height=height)
  if(show.plot) pl
  return(pl) # added on 071715
}
# the end of plot.bar7

load("/Volumes/data_work/Data6/bioconductor_R/Rclub2017_spring/Rclub-r4ds_Kazu.Nozue/summary.table.FT.rCol.Rdata")
# summary plot (FT)
FT.moreSAmutSASdata<-plot.bar7(trait="bolted days",title="FT",ylabel="days at bolting",data.input=merge(summary.table.FT.rCol.rSun,summary.table.FT.rCol.rShade,by="plant"),save.plot=F,show.plot=T,rownum=1,RFRratio=T)+ scale_fill_manual( values = c("high \nR/FR" = "red","low \nR/FR" = "darkred")) + scale_colour_manual( values = c("high \nR/FR" = "red","low \nR/FR" = "darkred"))
FT.moreSAmutSASdata
```
# 3.7.1 Exercises
```{r}
# 1. What is the default geom associated with stat_summary()? 
?geom_summary
#1.2 How could you rewrite the previous plot to use that geom function instead of the stat function?
# original
ggplot(data = diamonds) + geom_bar
  stat_summary(
    mapping = aes(x = cut, y = depth),
    fun.ymin = min,
    fun.ymax = max,
    fun.y = median
  )
# John's way
ggplot(data=diamonds,aes(x=cut,y=depth)) + geom_pointrange(stat = "summary", fun.ymin = min, fun.ymax = max, fun.y = median)

#2. What does geom_col() do? How is it different to geom_bar()?
?geom_col
?geom_bar

#3. Most geoms and stats come in pairs that are almost always used in concert. Read through the documentation and make a list of all the pairs. What do they have in common?

#4. What variables does stat_smooth() compute? What parameters control its behaviour?

#5. In our proportion bar chart, we need to set group = 1. Why? In other words what is the problem with these two graphs?
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, y = ..prop..))
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = color, y = ..prop..))
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = color, y = ..prop..,group=1))


```

# 3.8.1 Exercises
```{r}
ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "fill")

ggplot(data = diamonds, mapping = aes(x = cut, fill = clarity)) + 
  geom_bar(alpha = 1/5, position = "identity")
ggplot(data = diamonds, mapping = aes(x = cut, colour = clarity)) + 
  geom_bar(fill = NA, position = "identity")

ggplot(data = diamonds) + 
  geom_bar(mapping = aes(x = cut, fill = clarity), position = "dodge")

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))

ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy), position = "jitter")

#1. What is the problem with this plot? How could you improve it?
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + 
  geom_point()
# answer
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + 
  geom_jitter()

#2. What parameters to geom_jitter() control the amount of jittering?
?geom_jitter()
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + 
  geom_jitter()
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + 
  geom_jitter(width=0.05)

#3. Compare and contrast geom_jitter() with geom_count().
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + 
  geom_jitter()
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) + 
  geom_count() 

#4. What’s the default position adjustment for geom_boxplot()? Create a visualisation of the mpg dataset that demonstrates it.
# head(mpg)
# # A tibble: 6 × 11
#   manufacturer model displ  year   cyl      trans   drv   cty   hwy    fl   class
#          <chr> <chr> <dbl> <int> <int>      <chr> <chr> <int> <int> <chr>   <chr>
# 1         audi    a4   1.8  1999     4   auto(l5)     f    18    29     p compact
# 2         audi    a4   1.8  1999     4 manual(m5)     f    21    29     p compact
# 3         audi    a4   2.0  2008     4 manual(m6)     f    20    31     p compact
# 4         audi    a4   2.0  2008     4   auto(av)     f    21    30     p compact
# 5         audi    a4   2.8  1999     6   auto(l5)     f    16    26     p compact
# 6         audi    a4   2.8  1999     6 manual(m5)     f    18    26     p compact
?geom_boxplot() # default is "dodge"
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot(position="dodge")
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot(position="stack")
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot(position="stack")
ggplot(data = mpg, mapping = aes(x = drv, y = hwy)) + 
  geom_boxplot(position=position_dodge(4)) # ?



```
# 3.9 Coordinate systems
```{r}
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot()
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) + 
  geom_boxplot()+
  coord_flip()
#
nz <- map_data("nz")

ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", colour = "black")

ggplot(nz, aes(long, lat, group = group)) +
  geom_polygon(fill = "white", colour = "black") +
  coord_quickmap()
#
bar <- ggplot(data = diamonds) + 
  geom_bar(
    mapping = aes(x = cut, fill = cut), 
    show.legend = FALSE,
    width = 1
  ) + 
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)

bar + coord_flip()
bar + coord_polar()
# 
```
# 3.9.1 Exercises
```{r}
#1. Turn a stacked bar chart into a pie chart using coord_polar().
bar <- ggplot(data = diamonds) + 
  geom_bar(
    mapping = aes(x = cut, fill = cut), 
    show.legend = FALSE,
    width = 1
  ) + 
  theme(aspect.ratio = 1) +
  labs(x = NULL, y = NULL)

p<-ggplot(data=diamonds) + bar + coord_polar()
#
bar <- ggplot(data = diamonds, aes(cut,fill=color))
bar <- bar + geom_bar() + labs(x = NULL, y = NULL, title = "Cuts and Colors")
bar + coord_polar()

#2. What does labs() do? Read the documentation.

#3. What’s the difference between coord_quickmap() and coord_map()?
?coord_quickmap()
?coord_map()
#4. What does the plot below tell you about the relationship between city and highway mpg? Why is coord_fixed() important? What does geom_abline() do
?coord_fixed()
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_point()
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_abline()
ggplot(data = mpg, mapping = aes(x = cty, y = hwy)) +
  geom_point() + 
  geom_abline() +
  coord_fixed(ratio=1)

```
# 4.4 Practice
```{r}


```