---
title: "Kazu_Aug23"
author: "Kazu"
date: "8/22/2017"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```
# 19.5 Function arguments
```{r}
#Notice that when you call a function, you should place a space around = in function calls, and always put a space after a comma, not before (just like in regular English). Using whitespace makes it easier to skim the function for the important components.

# Good
average <- mean(feet / 12 + inches, na.rm = TRUE)

# Bad
average<-mean(feet/12+inches,na.rm=TRUE)

```
# 19.5.1 Choosing names
# 19.5.2 Checking values
```{r}

```
# 19.5.3 Dot-dot-dot (…)
```{r}
commas <- function(...) stringr::str_c(..., collapse = ", ")
commas(letters[1:10])
#> [1] "a, b, c, d, e, f, g, h, i, j"

rule <- function(..., pad = "-") {
  title <- paste0(...)
  width <- getOption("width") - nchar(title) - 5
  cat(title, " ", stringr::str_dup(pad, width), "\n", sep = "")
}
rule("Important output")
#
x <- c(1, 2)
sum(x, na.mr = TRUE) # typo. 4
sum(x, na.rm = TRUE) # no type. 3
```
# 19.5.4 Lazy evaluation
# 19.5.5 Exercises
```{r}
#1. What does commas(letters, collapse = "-") do? Why?
commas(letters, collapse = "-")
# Error in stringr::str_c(..., collapse = ", ") : 
#  formal argument "collapse" matched by multiple actual arguments
  
#2. It’d be nice if you could supply multiple characters to the pad argument, e.g. rule("Title", pad = "-+"). Why doesn’t this currently work? How could you fix it?
rule <- function(..., pad = "-") {
  title <- paste0(...)
  width <- getOption("width") - nchar(title) - 5
  cat(title, " ", stringr::str_dup(pad, width), "\n", sep = "")
}
rule("Title", pad = "-+")
rule("Title", pad = "-+*")

#3. What does the trim argument to mean() do? When might you use it?
?mean

x <- c(0:10, 50)
xm <- mean(x)
c(xm, mean(x, trim = 0.10))
mean(c(x,50), trim = 0.10)
mean(c(x,100), trim = 0.10)
mean(c(x,100), trim = 0.3)

#4. The default value for the method argument to cor() is c("pearson", "kendall", "spearman"). What does that mean? What value is used by default?
?cor
# choices of methods 
# "pearson" (default)

```
#19.6 Return values
# 19.6.1 Explicit return statements
```{r}

```
# 19.6.2 Writing pipeable functions
```{r}
# If you want to write your own pipeable functions, it’s important to think about the return value. Knowing the return value’s object type will mean that your pipeline will “just work”. For example, with dplyr and tidyr the object type is the data frame.

# There are two basic types of pipeable functions: transformations and side-effects. With transformations, an object is passed to the function’s first argument and a modified object is returned. With side-effects, the passed object is not transformed. Instead, the function performs an action on the object, like drawing a plot or saving a file. Side-effects functions should “invisibly” return the first argument, so that while they’re not printed they can still be used in a pipeline. For example, this simple function prints the number of missing values in a data frame:
show_missings <- function(df) {
  n <- sum(is.na(df))
  cat("Missing values: ", n, "\n", sep = "")
  
  invisible(df)
}
# If we call it interactively, the invisible() means that the input df doesn’t get printed out:
show_missings(mtcars)
# But it’s still there, it’s just not printed by default:
x <- show_missings(mtcars) 
#> Missing values: 0
class(x)
#> [1] "data.frame"
dim(x)
#> [1] 32 11
# And we can still use it in a pipe:
mtcars %>% 
  show_missings() %>% 
  mutate(mpg = ifelse(mpg < 20, NA, mpg)) %>% 
  show_missings() 
  
## (MO) should be invisible()? No.
show_missings <- function(df) {
  n <- sum(is.na(df))
  cat("Missing values: ", n, "\n", sep = "")
  return(df)
  #invisible(df)
}
```
# 19.7 Environment

# chapter 20: Vectors
## 20.1 Introduction
## 20.2 Vector basics
```{r}
# There are two types of vectors:
# Atomic vectors, of which there are six types: logical, integer, double, character, complex, and raw. Integer and double vectors are collectively known as numeric vectors.

# Lists, which are sometimes called recursive vectors because lists can contain other lists.

# The chief difference between atomic vectors and lists is that atomic vectors are homogeneous, while lists can be heterogeneous. There’s one other related object: NULL. NULL is often used to represent the absence of a vector (as opposed to NA which is used to represent the absence of a value in a vector). NULL typically behaves like a vector of length 0. Figure 20.1 summarises the interrelationships.
```
# 20.3 Important types of atomic vector
# 20.3.1 Logical
```{r}
1:10 %% 3 == 0
```
# 20.3.2 Numeric
```{r}
typeof(1)
#> [1] "double"
typeof(1L) # To make an integer, place an L after the number:
#> [1] "integer"
1.5L
#> [1] 1.5
#Warning message:
#integer literal 1.5L contains decimal; using numeric value 
```
# 20.3.3 Character
```{r}
#This reduces the amount of memory needed by duplicated strings. You can see this behaviour in practice with pryr::object_size():

x <- "This is a reasonably long string."
pryr::object_size(x)
#> 136 B

y <- rep(x, 1000)
pryr::object_size(y)
#> 8.13 kB
#y doesn’t take up 1,000x as much memory as x, because each element of y is just a pointer to that same string. A pointer is 8 bytes, so 1000 pointers to a 136 B string is 8 * 1000 + 136 = 8.13 kB.
```
# 20.3.4 Missing values
```{r}

```
# 20.3.5 Exercises
```{r}
#1. Describe the difference between is.finite(x) and !is.infinite(x).
?is.finite()
?is.infinite()
x<-c(Inf,0:8,-Inf,0.00,NA,NaN)
is.finite(x) # Inf, -Inf, NA, NaN are FALSE
is.infinite(x) # Inf, -Inf are TRUE
!is.infinite(x) # Inf, -Inf are FALSEm while NA, NaN are TRUE.

#2. Read the source code for dplyr::near() (Hint: to see the source code, drop the ()). How does it work?
dplyr::near
# function (x, y, tol = .Machine$double.eps^0.5) 
# {
#     abs(x - y) < tol
# }
?.Machine
.Machine
noquote(unlist(format(.Machine)))
# tol in dplyr:near is Tolerance of comparison.
# double.eps	
# the smallest positive floating-point number x such that 1 + x != 1. It equals double.base ^ ulp.digits if either double.base is 2 or double.rounding is 0; otherwise, it is (double.base ^ double.ulp.digits) / 2. Normally 2.220446e-16.

sqrt(2) ^ 2 == 2
near(sqrt(2) ^ 2, 2)

# This is a safe way of comparing if two vectors of floating point numbers are (pairwise) equal. This is safer than using ==, because it has a built in tolerance


#3. A logical vector can take 3 possible values. How many possible values can an integer vector take? How many possible values can a double take? Use google to do some research.
#?
#4. Brainstorm at least four functions that allow you to convert a double to an integer. How do they differ? Be precise.

x<-c(3.49999,4.4999999,4.50000000001)
typeof(x) # double
as.integer(x) # 3 4 4
round(x) #3 4 5
ceiling(x) # 4 5 5 
floor(x) #3 4 4

#5. What functions from the readr package allow you to turn a string into logical, integer, and double vector?
library(readr)
# under search..... #
parse_integer(c("1", "2", "3"))
parse_double(c("1", "2", "3.123"))
parse_number("$1,123,456.00")
parse_logical(1:10)
parse_logical(TRUE)
col_logical()
```