---
title: "Kazu_R-club_Aug30"
author: "Kazu"
date: "8/30/2017"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# 20.4 Using atomic vectors
## 20.4.1 Coercion
```{r}
typeof(c(TRUE, 1L))
#> [1] "integer"
typeof(c(1L, 1.5))
#> [1] "double"
typeof(c(1.5, "a"))
#> [1] "character"

```
## 20.4.2 Test functions
```{r, error=TRUE}
x <- sample(20, 100, replace = TRUE)
?is_logical()
is_logical(x)
is_integer()
```
## 20.4.3 Scalars and recycling rules
```{r error=TRUE}
sample(10) + 100
runif(10) > 0.5
1:10 + 1:2
1:10 + 1:3
tibble(x = 1:4, y = 1:2) # error
tibble(x = 1:4, y = rep(1:2, 2))
tibble(x = 1:4, y = rep(1:2, each = 2))
```
## 20.4.4 Naming vectors
```{r}
c(x = 1, y = 2, z = 4)
purrr::set_names(1:3, c("a", "b", "c"))

```
## 20.4.5 Subsetting
```{r, error=TRUE}
x <- c("one", "two", "three", "four", "five")
x[-1]
x[-1,3] # It’s an error to mix positive and negative values:

x <- c(10, 3, NA, 5, 8, 1, NA)

# All non-missing values of x
x[!is.na(x)]
#> [1] 10  3  5  8  1

# All even (or missing!) values of x
x[x %% 2 == 0]

```
## 20.4.6 Exercises
```{r, error=TRUE}
#1. What does mean(is.na(x)) tell you about a vector x? What about sum(!is.finite(x))?
x <- c(10, 3, NA, 5, 8, 1, NA)
mean(is.na(x)) # ratio of NA in x
sum(!is.finite(x)) # sum of numbers of not finite (= two "NA")
#2. Carefully read the documentation of is.vector(). What does it actually test for? Why does is.atomic() not agree with the definition of atomic vectors above?
?is.vector
is.vector(x)

is.atomic(x) 


#3. Compare and contrast setNames() with purrr::set_names().
?setNames
setNames( 1:3, c("foo", "bar", "baz") )
setNames( 1:3) # Error in setNames(1:3) : argument "nm" is missing, with no default

?purrr::set_names
purrr::set_names( 1:3, c("foo", "bar", "baz") )
purrr::set_names( 1:3)

#4. Create functions that take a vector as input and returns:
#4.1 The last value. Should you use [ or [[?
x
value_last<-function(x) {x[length(x)]}
value_last(x)
y<-sample(10,10)
y
value_last(y)
#4.2 The elements at even numbered positions.
pos_even<-function(x) {x[x %% 2 ==0]}
y
pos_even(y)

#4.3 Every element except the last value.
value_but_last<-function(x) {x[-length(x)]}
x
value_but_last(x)
#4.4 Only even numbers (and no missing values).
pos_even_noNA<-function(x) {
  temp<-x[!is.na(x)]
  temp[temp %% 2 ==0]
}
x
pos_even_noNA(x)
#5. Why is x[-which(x > 0)] not the same as x[x <= 0]?
?which
x<-rnorm(100)
x[-which(x > 0)]
x[x <= 0]
identical(x[-which(x > 0)],x[x <= 0]) # true



#6. What happens when you subset with a positive integer that’s bigger than the length of the vector? What happens when you subset with a name that doesn’t exist?
xx <- c("one", "two", "three", "four", "five")
xx[10]
#> [1] NA
xx["ten"]
#> [1] NA

```
# 20.5 Recursive vectors (lists)
## 20.5.1 Visualising lists
```{r}
a <- list(a = 1:3, b = "a string", c = pi, d = list(-1, -5))
str(a[1:2])
str(a[4])
str(a[[1]])
str(a[[4]])
a$a
a[["a"]]

```
## 20.5.3 Lists of condiments
```{r}

```
## 20.5.4 Exercises
```{r}
#1. Draw the following lists as nested sets:
#1.1 list(a, b, list(c, d), list(e, f))
#1.2 list(list(list(list(list(list(a))))))

#2. What happens if you subset a tibble as if you’re subsetting a list? What are the key differences between a list and a tibble?
tb <- tibble::tibble(x = 1:5, y = 5:1)
typeof(tb)
#> [1] "list"
attributes(tb)
tb[[1]]
names(tb)


```
# 20.6 Attributes
```{r}
x <- 1:10
attr(x, "greeting")
#> NULL
attr(x, "greeting") <- "Hi!"
attr(x, "farewell") <- "Bye!"
attributes(x)
```
# 20.7 Augmented vectors
## 20.7.1 Factors
```{r}

```
## 20.7.2 Dates and date-times
```{r}

```
## 20.7.3 Tibbles
```{r}

tb <- tibble::tibble(x = 1:5, y = 5:1)
typeof(tb)
#> [1] "list"
attributes(tb)
```

## 20.7.4 Exercises
```{r,error=TRUE}
#1. What does hms::hms(3600) return? How does it print? What primitive type is the augmented vector built on top of? What attributes does it use?
hms::hms(3600) # 01:00:00
hms::hms
?hms
#2. Try and make a tibble that has columns with different lengths. What happens?
tibble(a=1:10,b=letters[1:5]) 
# Error: Variables must be length 1 or 10.
# Problem variables: 'b'

#3. Based on the definition above, is it ok to have a list as a column of a tibble?
# I think so.
# needs to try

```