---
title: "Kazu_May24"
author: "Kazu"
date: "5/3/2017"
output: 
  html_document: 
    keep_md: yes
---

# Prerequisites
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
```
# 7.3 Variation
# 7.3.1 Visualising distributions
```{r}
## categorical
ggplot(data = diamonds) +geom_bar(mapping = aes(x = cut))
diamonds %>% 
  count(cut)
## continuous
ggplot(data = diamonds) +
  geom_histogram(mapping = aes(x = carat), binwidth = 0.5)
diamonds %>% 
  count(cut_width(carat, 0.5))
## smaller
smaller <- diamonds %>% 
  filter(carat < 3)
  
ggplot(data = smaller, mapping = aes(x = carat)) +
  geom_histogram(binwidth = 0.1)
## overlay multiple histograms in the same plot. Use geom_freqpoly()
ggplot(data = smaller, mapping = aes(x = carat, colour = cut)) +
  geom_freqpoly(binwidth = 0.1)
```
# 7.3.2 Typical values
```{r}
ggplot(data = smaller, mapping = aes(x = carat)) +
  geom_histogram(binwidth = 0.01)
ggplot(data = faithful, mapping = aes(x = eruptions)) + 
  geom_histogram(binwidth = 0.25)
```
# 7.3.3 Unusual values
```{r}
ggplot(diamonds) + 
  geom_histogram(mapping = aes(x = y), binwidth = 0.5)
ggplot(diamonds) + 
  geom_histogram(mapping = aes(x = y), binwidth = 0.5) +
  coord_cartesian(ylim = c(0, 50))
?coord_cartesian() # useful
## find strange data
unusual <- diamonds %>% 
  filter(y < 3 | y > 20) %>% 
  select(price, x, y, z) %>%
  arrange(y)
unusual
```
# 7.3.4 Exercises
```{r}
#1. Explore the distribution of each of the x, y, and z variables in diamonds. What do you learn? Think about a diamond and how you might decide which dimension is the length, width, and depth.
summary(diamonds)
ggplot(diamonds) + 
  geom_histogram(mapping = aes(x = x), binwidth = 0.5)
ggplot(diamonds) + 
  geom_histogram(mapping = aes(x = y), binwidth = 0.5)
ggplot(diamonds) + 
  geom_histogram(mapping = aes(x = z), binwidth = 0.5)
# x: height, y or z (length, width)


#2. Explore the distribution of price. Do you discover anything unusual or surprising? (Hint: Carefully think about the binwidth and make sure you try a wide range of values.)
summary(diamonds)
ggplot(diamonds) + 
  geom_histogram(mapping = aes(x = price), binwidth = 100)
diamonds %>% filter(between(price,1400,1600)) %>%
    ggplot() + 
  geom_histogram(mapping = aes(x = price), binwidth = 10) 
# missing price between $1450 and $1550

#3. How many diamonds are 0.99 carat? How many are 1 carat? What do you think is the cause of the difference?
diamonds %>% filter(carat==0.99) %>% count() # 23
diamonds %>% filter(carat==1) %>% count() # 1558
diamonds %>% filter(between(carat, 0.97,1.03)) %>% ggplot(mapping=aes(x=price,colour=factor(carat))) + geom_freqpoly() # ?
# because you can have higher prices above 0.99 carrat.
diamonds %>% filter(between(carat, 0.97,1.03)) %>% ggplot(mapping=aes(x=factor(carat), y=price)) + geom_violin()
  
#4. Compare and contrast coord_cartesian() vs xlim() or ylim() when zooming in on a histogram. What happens if you leave binwidth unset? What happens if you try and zoom so only half a bar shows?
# coord_cartesian(ylim = c(0, 20)). showing graph within ylim()
ggplot(diamonds) + 
  geom_histogram(mapping = aes(x = y), binwidth = 0.5) +
  coord_cartesian(ylim = c(0, 20))
# ylim(). Limit data within ylim range.
ggplot(diamonds) + 
  geom_histogram(mapping = aes(x = y), binwidth = 0.5) + 
  ylim(0, 20)
# coord_cartesian(ylim = c(0, 20)). showing graph within xlim()
ggplot(diamonds) + 
  geom_histogram(mapping = aes(x = y), binwidth = 0.5) +
  coord_cartesian(xlim = c(0, 10))
# xlim
ggplot(diamonds) + 
  geom_histogram(mapping = aes(x = y), binwidth = 0.5) + 
  xlim(0, 10) 
# If I leavce binwidth unse, ...
ggplot(diamonds) + 
  geom_histogram(mapping = aes(x = y)) +
  coord_cartesian(ylim = c(0, 20)) # `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
```
# 7.4 Missing values
```{r}
# If you’ve encountered unusual values in your dataset, and simply want to move on to the rest of your analysis, you have two options.
#1.  Drop the entire row with the strange values:
diamonds2 <- diamonds %>% 
  filter(between(y, 3, 20))
#2. Instead, I recommend replacing the unusual values with missing values. The easiest way to do this is to use mutate() to replace the variable with a modified copy. You can use the ifelse() function to replace unusual values with NA:
diamonds2 <- diamonds %>% 
  mutate(y = ifelse(y < 3 | y > 20, NA, y)) 
?ifelse
ggplot(data = diamonds2, mapping = aes(x = x, y = y)) + 
  geom_point()
ggplot(data = diamonds2, mapping = aes(x = x, y = y)) + 
  geom_point(na.rm = TRUE)
# 
nycflights13::flights %>% 
  mutate(
    cancelled = is.na(dep_time),
    sched_hour = sched_dep_time %/% 100,
    sched_min = sched_dep_time %% 100,
    sched_dep_time = sched_hour + sched_min / 60
  ) %>% 
  ggplot(mapping = aes(sched_dep_time)) + 
    geom_freqpoly(mapping = aes(colour = cancelled), binwidth = 1/4)
```
# 7.4.1 Exercises
```{r}
#1. What happens to missing values in a histogram? What happens to missing values in a bar chart? Why is there a difference?
flights.s<-nycflights13::flights %>% 
mutate(
    cancelled = is.na(dep_time),
    sched_hour = sched_dep_time %/% 100,
    sched_min = sched_dep_time %% 100,
    sched_dep_time = sched_hour + sched_min / 60
  )
ggplot(data=flights.s,aes(x=dep_time,fill=dest)) + geom_histogram(binwidth=100) + theme(legend.position = "none") # Warning message: Removed 8255 rows containing non-finite values (stat_bin). 
ggplot(data=flights.s,aes(x=dep_time,fill=dest)) + geom_bar() + theme(legend.position = "none")  # Warning message: Removed 8255 rows containing non-finite values (stat_count). 


#2. What does na.rm = TRUE do in mean() and sum()?
flights.s %>% group_by(dest) %>% summarise(delay.na.rm = mean(dep_delay, na.rm = TRUE),delay = mean(dep_delay, na.rm = FALSE),count.na=sum(is.na(dep_time))) # na.rm = TRUE is necesary to calculate mean 
flights.s %>% group_by(dest) %>% summarise(delay.na.rm = sum(dep_delay, na.rm = TRUE),delay = sum(dep_delay, na.rm = FALSE),count.na=sum(is.na(dep_time))) # na.rm = TRUE is not necesary to calculate mean 

```
# 7.5 Covariation
# 7.5.1 A categorical and continuous variable
```{r}
ggplot(data = diamonds, mapping = aes(x = price)) + 
  geom_freqpoly(mapping = aes(colour = cut), binwidth = 500)
ggplot(diamonds) + 
  geom_bar(mapping = aes(x = cut))
ggplot(data = diamonds, mapping = aes(x = price, y = ..density..)) + 
  geom_freqpoly(mapping = aes(colour = cut), binwidth = 500)
ggplot(data = diamonds, mapping = aes(x = cut, y = price)) +
  geom_boxplot()
ggplot(data = mpg, mapping = aes(x = class, y = hwy)) +
  geom_boxplot()
#To make the trend easier to see, we can reorder class based on the median value of hwy:
ggplot(data = mpg) +
  geom_boxplot(mapping = aes(x = reorder(class, hwy, FUN = median), y = hwy))
# flip
ggplot(data = mpg) +
  geom_boxplot(mapping = aes(x = reorder(class, hwy, FUN = median), y = hwy)) +
  coord_flip()
```
# 7.5.1.1 Exercises
```{r}
#1. Use what you’ve learned to improve the visualisation of the departure times of cancelled vs. non-cancelled flights.
## I assumed that this is talking about scheduled departure times
flights %>% mutate(cancelled=is.na(dep_time)) %>% group_by(sched_dep_time) %>% summarise(count.na=sum(is.na(dep_time)),prop.cancel=count.na/n()*100) %>%  ggplot(aes(x=sched_dep_time,y=prop.cancel)) + geom_boxplot(aes(group = cut_width(sched_dep_time, 30))) + coord_cartesian(ylim = c(0, 60))
  
#2. What variable in the diamonds dataset is most important for predicting the price of a diamond? How is that variable correlated with cut? Why does the combination of those two relationships lead to lower quality diamonds being more expensive?
ggplot(diamonds,aes(x=carat,y=price)) + geom_point()
ggplot(diamonds,aes(x=cut,y=price)) + geom_boxplot()
ggplot(diamonds) + geom_boxplot(aes(x=reorder(color,price, FUN = median),y=price))
ggplot(diamonds,aes(x=depth,y=price)) + geom_boxplot(aes(group=cut_width(depth,5))) # why width are not equal?
ggplot(diamonds,aes(x=table,y=price)) + geom_boxplot(aes(group=cut_width(table,5)))
  
#3. Install the ggstance package, and create a horizontal boxplot. How does this compare to using coord_flip()?
install.packages("ggstance")
library(ggstance)
ggplot(diamonds,aes(x=table,y=price)) + geom_boxploth(aes(group=cut_width(table,5))) #?

#4. One problem with boxplots is that they were developed in an era of much smaller datasets and tend to display a prohibitively large number of “outlying values”. One approach to remedy this problem is the letter value plot. Install the lvplot package, and try using geom_lv() to display the distribution of price vs cut. What do you learn? How do you interpret the plots?
install.packages("lvplot")
library(lvplot)
?geom_lv
p <- ggplot(mpg, aes(class, hwy))
p + geom_lv(aes(fill=..LV..)) + scale_fill_brewer()
# Error: GeomLv was built with an incompatible version of ggproto.
# Please reinstall the package that provides this extension.
# solution?


#5. Compare and contrast geom_violin() with a facetted geom_histogram(), or a coloured geom_freqpoly(). What are the pros and cons of each method?
ggplot(diamonds) + geom_violin(aes(x=reorder(color,price, FUN = median),y=price))

ggplot(diamonds, aes(x=price)) + geom_histogram(binwidth=100) + facet_grid(.~reorder(color,price,FUN=median),scale="free") + coord_flip()

ggplot(diamonds, aes(x=price,color=color)) + geom_freqpoly(binwidth=100) + coord_flip()

#6. If you have a small dataset, it’s sometimes useful to use geom_jitter() to see the relationship between a continuous and categorical variable. The ggbeeswarm package provides a number of methods similar to geom_jitter(). List them and briefly describe what each one does.
install.packages("ggbeeswarm")
library(ggbeeswarm)


```
# 7.5.2 Two categorical variables
```{r}
ggplot(data = diamonds) +
  geom_count(mapping = aes(x = cut, y = color))
diamonds %>% 
  count(color, cut)
# geom_tile
diamonds %>% 
  count(color, cut) %>%  
  ggplot(mapping = aes(x = color, y = cut)) +
    geom_tile(mapping = aes(fill = n))

```
# 7.5.2.1 Exercises
```{r}
#1. How could you rescale the count dataset above to more clearly show the distribution of cut within colour, or colour within cut?
diamonds %>%
  ggplot(mapping=aes(x=cut)) + geom_bar() + facet_grid(color~.)
diamonds %>%
  ggplot(mapping=aes(x=color)) + geom_bar() + facet_grid(cut~.)

#2. Use geom_tile() together with dplyr to explore how average flight delays vary by destination and month of year. What makes the plot difficult to read? How could you improve it?
library(nycflights13)
average.delay.month.summary<-flights %>% group_by(dest,month) %>% summarise(av.flight.delay=mean(dep_delay,na.rm=T)) %>% filter(!is.na(av.flight.delay))
average.delay.month.summary
ggplot(average.delay.month.summary, aes(x=month,y=dest)) + geom_tile(mappint=aes(fill=av.flight.delay))




#3. Why is it slightly better to use aes(x = color, y = cut) rather than aes(x = cut, y = color) in the example above?

```
