---
title: "Kazu_May10"
author: "Kazu"
date: "5/3/2017"
output: 
  html_document: 
    keep_md: yes
---

# Prerequisites
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(nycflights13)
library(tidyverse)
```
# 5 Data transformation
## 5.1.3 dplyr basics
```{r}
?flights
flights
# Pick observations by their values (filter()).
# Reorder the rows (arrange()).
# Pick variables by their names (select()).
# Create new variables with functions of existing variables (mutate()).
# Collapse many values down to a single summary (summarise()).
# These can all be used in conjunction with group_by() which changes the scope of each function from operating on the entire dataset to operating on it group-by-group. These six functions provide the verbs for a language of data manipulation.
# 
# All verbs work similarly:
# 
# The first argument is a data frame.
# 
# The subsequent arguments describe what to do with the data frame, using the variable names (without quotes).
# 
# The result is a new data frame.

```
# 5.2 Filter rows with filter()
```{r}
filter(flights, month == 1, day == 1) # prints out the results
jan1 <- filter(flights, month == 1, day == 1) # saves them to a variable
(dec25 <- filter(flights, month == 12, day == 25)) # both
```

# 5.2.1 Comparisons; 5.2.2 Logical operators
```{r}
filter(flights, month == 11 | month == 12)
filter(flights, xor(month == 11,month == 12)) # my own
filter(flights, month == 11 & year== 2013) # my own
filter(flights, month == 11 && year== 2013) #  tried from ?xor

nov_dec <- filter(flights, month %in% c(11, 12))
filter(flights, !(arr_delay > 120 | dep_delay > 120))
filter(flights, arr_delay <= 120, dep_delay <= 120)

```
# 5.2.3 Missing values
```{r}
df <- tibble(x = c(1, NA, 3)) # tibble() is a trimmed down version of data.frame(). Look ?tibble
filter(df, x > 1)
filter(df, is.na(x) | x > 1)
```
#5.2.4 Exercises
```{r}
#1.Find all flights that
# 
# Had an arrival delay of two or more hours
# Flew to Houston (IAH or HOU)
# Were operated by United, American, or Delta
# Departed in summer (July, August, and September)
# Arrived more than two hours late, but didn’t leave late
# Were delayed by at least an hour, but made up over 30 minutes in flight
# Departed between midnight and 6am (inclusive)
filter(flights, arr_delay>2)
filter(flights, dest %in% c("IAH","HOU"))
filter(flights, carrier %in% c("UA","AA","DL"))
filter(flights, month %in% c(7,8,9))
filter(flights, dep_delay<1)
filter(flights, dep_delay>=1 & arr_delay<dep_delay)
filter(flights, dep_time >0 & dep_time<0600)

#2. Another useful dplyr filtering helper is between(). What does it do? Can you use it to simplify the code needed to answer the previous challenges?
?between
filter(flights, between(month,7,9))
filter(flights, between(dep_time,0,0600)) %>% arrange(dep_time)
filter(flights, between(dep_time,0000,0600)) %>% arrange(dep_time)

#3. How many flights have a missing dep_time? What other variables are missing? What might these rows represent?
flights.miss.dep_time<-filter(flights,is.na(dep_time))
apply(flights.miss.dep_time,2,is.na)
summary(flights.miss.dep_time) # better way? # dep_delay, arr_time, arr_delay,air_time

#4. Why is NA ^ 0 not missing? Why is NA | TRUE not missing? Why is FALSE & NA not missing? Can you figure out the general rule? (NA * 0 is a tricky counterexample!)
# ?

```
# 5.3 Arrange rows with arrange()
```{r}
arrange(flights, year, month, day)
arrange(flights, desc(arr_delay))
df <- tibble(x = c(5, 2, NA))
arrange(df, x)
```
# 5.3.1 Exercises
```{r}
#1. How could you use arrange() to sort all missing values to the start? (Hint: use is.na()).
arrange(flights, !is.na(arr_delay))

#2. Sort flights to find the most delayed flights. Find the flights that left earliest.
arrange(flights, desc(arr_delay))
arrange(flights,!desc(dep_time)) # reverse order

#3. Sort flights to find the fastest flights.

arrange(flights,!desc(distance/air_time)) # reverse order
## another way
mutate(flights,speed= distance / air_time) # does not work,. why?
# select(flights, speed) # Error in eval(expr, envir, enclos) : object 'speed' not found
#arrange(flights,!desc(speed)) # reverse order

#4. Which flights travelled the longest? Which travelled the shortest?
arrange(flights,desc(distance))
arrange(flights,!desc(distance))
### What is the merit of "tibble"?

```
#5.4.1 Exercises
```{r}
#1. Brainstorm as many ways as possible to select dep_time, dep_delay, arr_time, and arr_delay from flights.
select(flights,dep_time, dep_delay,arr_time,arr_delay)
select(flights,starts_with("dep"),starts_with("arr"))
flights[,c("dep_time","dep_delay","arr_time","arr_delay")]
flights[,colnames(flights) %in% c("dep_time","dep_delay","arr_time","arr_delay")]

#2. What happens if you include the name of a variable multiple times in a select() call?
select(flights, dep_time,dep_time, dep_time) # only showing once

#3. What does the one_of() function do? Why might it be helpful in conjunction with this vector?
vars <- c("year", "month", "day", "dep_delay", "arr_delay")
select(flights,one_of(vars))
select(flights,one_of(vars),3)

#select(flights, vars) # does not work

#4. Does the result of running the following code surprise you? How do the select helpers deal with case by default? How can you change that default?
select(flights, contains("TIME")) #ignore.case is TRUE, the default, ignores case when matching names.
select(flights, contains("TIME",ignore.case=FALSE)) # none

```
# 5.5 Add new variables with mutate()
```{r}
flights_sml <- select(flights, 
  year:day, 
  ends_with("delay"), 
  distance, 
  air_time
)
mutate(flights_sml,
  gain = arr_delay - dep_delay,
  speed = distance / air_time * 60
)
# View(flights_sml) # view all columns 
## 
mutate(flights_sml,
  gain = arr_delay - dep_delay,
  hours = air_time / 60,
  gain_per_hour = gain / hours
)
# If you only want to keep the new variables, use transmute():
transmute(flights,
  gain = arr_delay - dep_delay,
  hours = air_time / 60,
  gain_per_hour = gain / hours
)

```
# 5.5.1 Useful creation functions
```{r}
transmute(flights,
  dep_time,
  hour = dep_time %/% 100,
  minute = dep_time %% 100
)
# lead

# lag 
# Use order_by if data not already ordered (from ?lag)
df <- data.frame(year = 2000:2005, value = (0:5) ^ 2)
scrambled <- df[sample(nrow(df)), ]
scrambled
wrong <- mutate(scrambled, prev = lag(value))
arrange(wrong, year)
right <- mutate(scrambled, prev = lag(value, order_by = year))
arrange(right, year)
```
# 5.5.2 Exercises
```{r}
# 1. Currently dep_time and sched_dep_time are convenient to look at, but hard to compute with because they’re not really continuous numbers. Convert them to a more convenient representation of number of minutes since midnight.
# mutate(flights,dep_time_min=dep_time-0); flights$dep_time_min # does not work
# as.POSIXct(flights$dep_time,format="%H%M") # does not work
# as.POSIXct.numeric(flights$dep_time,format="%H%M") # does not work
# as.POSIXct(as.character(flights$dep_time),format="%H%M") # does work only for two digits hour
# as.POSIXct(as.character(flights$dep_time),format="%I%M") # does work only for two digits hour
# strptime(flights$dep_time,"%H%M")[1:10] # does not work
#strptime(sprintf("%04d",flights$dep_time),"%H%M")[1:10] # does work
mutate(flights,
       dep_time_min=as.POSIXct(sprintf("%04d",flights$dep_time),format="%H%M")-as.POSIXct("0000",format="%H%M"))
# colnames(flights) # does not work


#2. Compare air_time with arr_time - dep_time. What do you expect to see? What do you see? What do you need to do to fix it?
transmute(flights,air_time,dep_time,arr_time - dep_time)
# library(lubridate)
# needs to use appropriate date/time format (I do not remember how to say)
# hm(as.character(flights$dep_time)) # does not work
# hm(as.character(flights$dep_time)) # does not work
transmute(flights,air_time,dep_time,dep_time_delay=as.POSIXct(sprintf("%04d",flights$arr_time),format="%H%M") - as.POSIXct(sprintf("%04d",flights$dep_time),format="%H%M"))


#3. Compare dep_time, sched_dep_time, and dep_delay. How would you expect those three numbers to be related?
transmute(flights,dep_time,sched_dep_time,dep_delay) #dep_time - sched_dep_time = dep_delay

#4. Find the 10 most delayed flights using a ranking function. How do you want to handle ties? Carefully read the documentation for min_rank().
arrange(flights,!desc(dep_delay))# does  work
arrange(flights,min_rank(dep_delay))# does  work


#5. What does 1:3 + 1:10 return? Why?
1:3 + 1:10 
c(1+1,2+2, 3+3, 1+4,2+5,3+6,1+7,2+8,3+9,1+10)

#6. What trigonometric functions does R provide?
# x <- seq(-3, 7, by = 1/8)
# 
# cos(x)
# sin(x)
# tan(x)
# 
# acos(x)
# asin(x)
# atan(x)
# atan2(y, x)
# 
# cospi(x)
# sinpi(x)
# tanpi(x)
# 
# head(x)
# tx <- cbind(x, cos(pi*x), cospi(x), sin(pi*x), sinpi(x),
#                tan(pi*x), tanpi(x), deparse.level=2)
# op <- options(digits = 4, width = 90) # for nice formatting
# head(tx)
```
