---
title: "Kazu_May17"
author: "Kazu"
date: "5/3/2017"
output: 
  html_document: 
    keep_md: yes
---

# Prerequisites
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(nycflights13)
library(tidyverse)
```
# 5 Data transformation
#5.6 Grouped summaries with summarise()
```{r}
summarise(flights, delay = mean(dep_delay, na.rm = TRUE))
by_day <- group_by(flights, year, month, day)
summarise(by_day, delay = mean(dep_delay, na.rm = TRUE))

```
# 5.6.1 Combining multiple operations with the pipe
```{r}
by_dest <- group_by(flights, dest)
delay <- summarise(by_dest,
  count = n(),
  dist = mean(distance, na.rm = TRUE),
  delay = mean(arr_delay, na.rm = TRUE)
)
delay <- filter(delay, count > 20, dest != "HNL")

# It looks like delays increase with distance up to ~750 miles 
# and then decrease. Maybe as flights get longer there's more 
# ability to make up delays in the air?
ggplot(data = delay, mapping = aes(x = dist, y = delay)) +
  geom_point(aes(size = count), alpha = 1/3) +
  geom_smooth(se = FALSE)

```
# 5.6.2 Missing values
```{r}
flights %>% 
  group_by(year, month, day) %>% 
  summarise(mean = mean(dep_delay, na.rm = TRUE))
# In this case, where missing values represent cancelled flights, we could also tackle the problem by first removing the cancelled flights. We’ll save this dataset so we can reuse in the next few examples.
not_cancelled <- flights %>% 
  filter(!is.na(dep_delay), !is.na(arr_delay))

not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(mean = mean(dep_delay))
```
# 5.6.3 Counts
```{r}
delays <- not_cancelled %>% 
  group_by(tailnum) %>% 
  summarise(
    delay = mean(arr_delay)
  )

ggplot(data = delays, mapping = aes(x = delay)) + 
  geom_freqpoly(binwidth = 10)
## scatter plot
delays <- not_cancelled %>% 
  group_by(tailnum) %>% 
  summarise(
    delay = mean(arr_delay, na.rm = TRUE),
    n = n()
  )

ggplot(data = delays, mapping = aes(x = n, y = delay)) + 
  geom_point(alpha = 1/10)
## depending on group size?
delays %>% 
  filter(n > 25) %>% 
  ggplot(mapping = aes(x = n, y = delay)) + 
    geom_point(alpha = 1/10)
```
# 5.6.4 Useful summary functions
```{r}
not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(
    avg_delay1 = mean(arr_delay),
    avg_delay2 = mean(arr_delay[arr_delay > 0]) # the average positive delay
  )
## Measures of spread
not_cancelled %>% 
  group_by(dest) %>% 
  summarise(distance_sd = sd(distance)) %>% 
  arrange(desc(distance_sd))
## Measures of rank
# When do the first and last flights leave each day?
not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(
    first = min(dep_time),
    last = max(dep_time)
  )
## Measures of position
not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(
    first_dep = first(dep_time), 
    last_dep = last(dep_time)
  )
## These functions are complementary to filtering on ranks. Filtering gives you all variables, with each observation in a separate row
not_cancelled %>% 
  group_by(year, month, day) %>% 
  mutate(r = min_rank(desc(dep_time))) %>% 
  filter(r %in% range(r))
## counts
### Which destinations have the most carriers?
not_cancelled %>% 
  group_by(dest) %>% 
  summarise(carriers = n_distinct(carrier)) %>% 
  arrange(desc(carriers))
### Counts are so useful that dplyr provides a simple helper if all you want is a count:
not_cancelled %>% count(dest)
### You can optionally provide a weight variable. For example, you could use this to “count” (sum) the total number of miles a plane flew:
not_cancelled %>% count(tailnum, wt = distance)
### Counts and proportions of logical values: sum(x > 10), mean(y == 0). When used with numeric functions, TRUE is converted to 1 and FALSE to 0. This makes sum() and mean() very useful: sum(x) gives the number of TRUEs in x, and mean(x) gives the proportion.
#### How many flights left before 5am? (these usually indicate delayed
#### flights from the previous day)
not_cancelled %>% group_by(year, month, day) %>% 
  summarise(n_early = sum(dep_time < 500))
#### What proportion of flights are delayed by more than an hour?
not_cancelled %>% 
  group_by(year, month, day) %>% 
  summarise(hour_perc = mean(arr_delay > 60))
```
# 5.6.5 Grouping by multiple variables
```{r}
daily <- group_by(flights, year, month, day)
(per_day   <- summarise(daily, flights = n()))
(per_month <- summarise(per_day, flights = sum(flights)))
(per_year  <- summarise(per_month, flights = sum(flights)))
```
# 5.6.6 Ungrouping
```{r}
daily %>% 
  ungroup() %>%             # no longer grouped by date
  summarise(flights = n())  # all flights
```

# 5.6.7 Exercises
```{r}
#1. Brainstorm at least 5 different ways to assess the typical delay characteristics of a group of flights. Consider the following scenarios:
## A flight is 15 minutes early 50% of the time, and 15 minutes late 50% of the time.
colnames(not_cancelled)
## early ver1
fif.min.early.1 <- not_cancelled %>% group_by(tailnum) %>% summarise(fifteen.mim.early=sum(dep_delay == -15),num=n(),percent.fifteen.mim.early=fifteen.mim.early/num * 100)
fif.minearly.1%>% filter(percent.fifteen.mim.early >= 50) %>% arrange(desc(percent.fifteen.mim.early))
## early ver2
fif.min.early.2<- not_cancelled %>% 
  group_by(tailnum) %>% 
  summarise(fifteen.mim.early_perc2 = mean(dep_delay == -15) * 100) # mean of T/F is proportion!
# correlation of ver1 and ver2
cor.1.2<-inner_join(fif.min.early.1,fif.min.early.2,by="tailnum")
ggplot(data=cor.1.2,aes(x=percent.fifteen.mim.early,y=fifteen.mim.early_perc2)) + geom_point()

## late 
### ver1
fif.min.late1<- not_cancelled %>% 
  group_by(tailnum) %>% 
  summarise(fifteen.mim.delay=sum(dep_delay == 15),num=n(),percent.fifteen.mim.delay=fifteen.mim.delay/num * 100) %>% filter(percent.fifteen.mim.delay >= 50) %>% 
  arrange(desc(percent.fifteen.mim.delay))
### ver2
fif.min.late2<- not_cancelled %>% 
  group_by(tailnum) %>% 
  summarise(fifteen.mim.late_perc2 = mean(dep_delay == 15) * 100) 

## A flight is always 10 minutes late.
### ver1
not_cancelled %>% group_by(tailnum) %>% summarise(ten.mim.delay=sum(dep_delay ==10),num=n(),percent.ten.mim.delay=ten.mim.delay/num * 100) %>% ggplot() + geom_histogram(mapping=aes(x=percent.ten.mim.delay))

not_cancelled %>% group_by(tailnum) %>% summarise(ten.mim.delay=sum(dep_delay ==10),num=n(),percent.ten.mim.delay=ten.mim.delay/num * 100) %>% arrange(desc(percent.ten.mim.delay)) # none
### ver2
ten.min.late2<- not_cancelled %>% 
  group_by(tailnum) %>% 
  summarise(ten.mim.late_perc2 = mean(dep_delay == 10) * 100) 
arrange(ten.min.late2,desc(ten.mim.late_perc2)) # none

## A flight is 30 minutes early 50% of the time, and 30 minutes late 50% of the time.
not_cancelled.selected<- not_cancelled %>% 
  group_by(tailnum) %>% 
  summarise(thirty.mim.early=sum(dep_delay == -30),thirty.mim.delay=sum(dep_delay ==30),num=n(),percent.thirty.mim.early=thirty.mim.early/num * 100, percent.thirty.mim.delay=thirty.mim.delay/num * 100)


#%>% filter(percent.thirty.mim.early>30 & percent.thirty.mim.delay>50)
## 99% of the time a flight is on time. 1% of the time it’s 2 hours late.

#2. Which is more important: arrival delay or departure delay?

#3. Come up with another approach that will give you the same output as not_cancelled %>% count(dest) and not_cancelled %>% count(tailnum, wt = distance) (without using count()).

#4. Our definition of cancelled flights (is.na(dep_delay) | is.na(arr_delay) ) is slightly suboptimal. Why? Which is the most important column?

#5. Look at the number of cancelled flights per day. Is there a pattern? Is the proportion of cancelled flights related to the average delay?

#6. Which carrier has the worst delays? Challenge: can you disentangle the effects of bad airports vs. bad carriers? Why/why not? (Hint: think about flights %>% group_by(carrier, dest) %>% summarise(n()))

#7. What does the sort argument to count() do. When might you use it?
```
# 5.7 Grouped mutates (and filters)
```{r}
## find worst members of each group
### from previous section
flights_sml <- select(flights, 
  year:day, 
  ends_with("delay"), 
  distance, 
  air_time
)
mutate(flights_sml,
  gain = arr_delay - dep_delay,
  speed = distance / air_time * 60
)
# View(flights_sml) # view all columns 
## 
mutate(flights_sml,
  gain = arr_delay - dep_delay,
  hours = air_time / 60,
  gain_per_hour = gain / hours
)

flights_sml %>% 
  group_by(year, month, day) %>%
  filter(rank(desc(arr_delay)) < 10)
## Find all groups bigger than a threshold:
popular_dests <- flights %>% 
  group_by(dest) %>% 
  filter(n() > 365)
popular_dests
## Standardise to compute per group metrics:
popular_dests %>% 
  filter(arr_delay > 0) %>% 
  mutate(prop_delay = arr_delay / sum(arr_delay)) %>% 
  select(year:day, dest, arr_delay, prop_delay)

```
# 5.7.1 Exercises
```{r}
#1. Refer back to the lists of useful mutate and filtering functions. Describe how each operation changes when you combine it with grouping.

#2. Which plane (tailnum) has the worst on-time record?
summary.online<-
  not_cancelled %>% group_by(tailnum) %>%
  summarise(dep.ontime=mean(dep_delay==0), arr.ontime=mean(arr_delay==0))
filter(summary.online,dep.ontime==0 & arr.ontime==0)
ggplot(summary.online, aes(x=dep.ontime,y=arr.ontime)) + geom_point(alpha=0.5)

#3. What time of day should you fly if you want to avoid delays as much as possible?
summary.delay<-not_cancelled %>% group_by(month, day) %>%
  summarise(dep.delay=mean(dep_delay),arr.delay=mean(arr_delay))
library(reshape2)
summary.delay.melt<-melt(summary.delay,id.var=c("month","day"))
ggplot(summary.delay.melt,aes(x=day,y=value,color=variable)) + geom_point() + facet_grid(month~.)

#4. For each destination, compute the total minutes of delay. For each, flight, compute the proportion of the total delay for its destination.
summary.delay2<-not_cancelled %>% group_by(dest) %>%
  summarise(dest.delay.total=sum(dep_delay))
summary.delay3<-not_cancelled %>% group_by(dest,tailnum) %>%
  summarise(delay.total=sum(dep_delay))
summary.delay4<-inner_join(summary.delay2,summary.delay3,by="dest")
mutate(summary.delay4,delay_proc=delay.total/dest.delay.total)

#5. Delays are typically temporally correlated: even once the problem that caused the initial delay has been resolved, later flights are delayed to allow earlier flights to leave. Using lag() explore how the delay of a flight is related to the delay of the immediately preceding flight.

#6. Look at each destination. Can you find flights that are suspiciously fast? (i.e. flights that represent a potential data entry error). Compute the air time a flight relative to the shortest flight to that destination. Which flights were most delayed in the air?

#7. Find all destinations that are flown by at least two carriers. Use that information to rank the carriers.

# For each plane, count the number of flights before the first delay of greater than 1 hour.
```
